kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: log-collection
  labels:
    argocd.argoproj.io/instance: log-collection
spec:
  to:
    kind: Service
    name: log-collection-a
    weight: 50
  alternateBackends:
  - kind: Service
    name: log-collection-b
    weight: 100 
  port:
    targetPort: 8080
  wildcardPolicy: None
