kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: log-collection
  labels:
    argocd.argoproj.io/instance: log-collection
spec:
  host: log-collection-argotest2.apps.cluster-3895.3895.example.opentlc.com
  to:
    kind: Service
    name: log-collection
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
